name: CD Pipeline - Production

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI Pipeline"]
    branches:
      - main
    types:
      - completed

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    