name: CD Pipeline - Production

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI Pipeline"]
    branches:
      - main
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    with:
      python-version: '3.12'
    secrets: inherit
    