name: Project Columns Setup

on:
  workflow_dispatch:

jobs:
  setup-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Create Project Columns
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER="ranog"
          REPO="validate-jwt"
          PROJECT_NUMBER=1
          
          # Get the project ID
          PROJECT_ID=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/$OWNER/$REPO/projects" | jq ".[] | select(.name == \"validate-jwt\") | .id")
          
          # Create columns
          for COLUMN in "To Do" "In Progress" "Done"
          do
            curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"name\": \"$COLUMN\"}" \
            "https://api.github.com/projects/$PROJECT_ID/columns"
          done
